/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Ventana de inicio de sesion del sistema GymPower.
 * Permite a clientes y entrenadores autenticarse en el sistema.
 * Utiliza JSpinner para seleccionar el tipo de usuario (componente adicional).
 * @author andre
 */
public class InicioSesion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioSesion.class.getName());

    /**
     * Constructor: crea la ventana de inicio de sesion.
     */
    public InicioSesion() {
        initComponents();
        setLocationRelativeTo(null);
        cargarIconoBoton();
        setVisible(true);
    }

    /**
     * Intenta cargar un icono en el boton de entrar.
     * Si el recurso no existe, el boton queda solo con texto.
     */
    private void cargarIconoBoton() {
        try {
            java.net.URL url = getClass().getResource("/imagenes/entrar.png");
            if (url != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
                java.awt.Image img = icon.getImage().getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
                btnEntrar.setIcon(new javax.swing.ImageIcon(img));
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "Icono no encontrado", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblTipoUsuario = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        lblIntentos = new javax.swing.JLabel();
        spnIntentos = new javax.swing.JSpinner();
        btnEntrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesion - GymPower");
        setResizable(false);

        lblTipoUsuario.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblTipoUsuario.setText("Tipo de usuario:");
        lblTipoUsuario.setName("lblTipoUsuario");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Cliente", "Entrenador"}));
        cmbTipo.setName("cmbTipo");

        lblUsuario.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblUsuario.setText("Usuario:");
        lblUsuario.setName("lblUsuario");

        txtUsuario.setName("txtUsuario");

        lblContrasena.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblContrasena.setText("Contrasena:");
        lblContrasena.setName("lblContrasena");

        txtContrasena.setName("txtContrasena");
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        // JSpinner: componente no explicado en clase
        // Muestra cuantos intentos de sesion lleva el usuario (informativo)
        lblIntentos.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        lblIntentos.setForeground(new java.awt.Color(130, 130, 130));
        lblIntentos.setText("Intentos:");
        lblIntentos.setName("lblIntentos");

        spnIntentos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnIntentos.setEnabled(false);
        spnIntentos.setName("spnIntentos");

        btnEntrar.setBackground(new java.awt.Color(52, 120, 200));
        btnEntrar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.setName("btnEntrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setName("btnVolver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoUsuario)
                    .addComponent(lblUsuario)
                    .addComponent(lblContrasena)
                    .addComponent(lblIntentos))
                .addGap(30, 30, 30)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(txtUsuario)
                    .addComponent(txtContrasena)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addComponent(spnIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(100, 100, 100))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntentos)
                    .addComponent(spnIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * Permite iniciar sesion presionando Enter en el campo de contrasena.
     * @param evt evento de accion del campo de texto
     */
    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {
        iniciarSesion();
    }

    /**
     * Valida las credenciales y redirige al menu correspondiente.
     * @param evt evento del boton Entrar
     */
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {
        iniciarSesion();
    }

    /**
     * Vuelve a la ventana de inicio.
     * @param evt evento del boton Volver
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {
        new Inicio();
        dispose();
    }

    /**
     * Logica principal de autenticacion.
     * Verifica usuario y contrasena segun el tipo seleccionado.
     * Incrementa el contador de intentos con el JSpinner.
     */
    private void iniciarSesion() {
        String usuario = txtUsuario.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();
        String tipo = (String) cmbTipo.getSelectedItem();

        // Incrementar contador de intentos en el JSpinner
        int intentos = (int) spnIntentos.getValue();
        spnIntentos.setValue(intentos + 1);

        if (usuario.isEmpty() || contrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ("Cliente".equals(tipo)) {
            Cliente c = DataManager.buscarCliente(usuario, contrasena);
            if (c != null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bienvenido, " + c.getNombre() + "!", "Acceso exitoso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                new MenuCliente(c);
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuario o contrasena incorrectos.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            Entrenador e = DataManager.buscarEntrenador(usuario, contrasena);
            if (e != null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Bienvenido, " + e.getNombre() + "!", "Acceso exitoso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                new MenuEntrenador(e);
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuario o contrasena incorrectos.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Metodo principal para ejecutar directamente esta ventana.
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JSpinner spnIntentos;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration
}
