/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Ventana de inicio del sistema GymPower.
 * Permite al usuario elegir entre iniciar sesion o registrarse.
 * @author andre
 */
public class Inicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Constructor: inicializa los componentes de la ventana de inicio.
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        cambiarIconoAplicacion();
        cargarIconosBotones();
        setVisible(true);
    }

    /**
     * Cambia el icono de la barra de titulo de la ventana (reemplaza el icono de Java).
     * Busca el archivo icono.png dentro de la carpeta imagenes del proyecto.
     * Si no se encuentra, el icono por defecto de Java permanece sin errores.
     */
    private void cambiarIconoAplicacion() {
        try {
            java.net.URL urlIcono = getClass().getResource("/imagenes/IconoVentana.png");
            if (urlIcono != null) {
                java.awt.Image icono = new javax.swing.ImageIcon(urlIcono).getImage();
                setIconImage(icono);
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo cargar el icono de la aplicacion", ex);
        }
    }

    /**
     * Carga imagenes/iconos en los botones si estan disponibles.
     * Si no se encuentran los recursos, los botones muestran solo texto.
     */
    private void cargarIconosBotones() {
        try {
            // Icono para el boton de iniciar sesion
            java.net.URL urlLogin = getClass().getResource("/imagenes/Login.png");
            if (urlLogin != null) {
                javax.swing.ImageIcon iconLogin = new javax.swing.ImageIcon(urlLogin);
                java.awt.Image imgLogin = iconLogin.getImage().getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
                btnIniciarSesion.setIcon(new javax.swing.ImageIcon(imgLogin));
            }
            // Icono para el boton de registrarse
            java.net.URL urlReg = getClass().getResource("/imagenes/registro.png");
            if (urlReg != null) {
                javax.swing.ImageIcon iconReg = new javax.swing.ImageIcon(urlReg);
                java.awt.Image imgReg = iconReg.getImage().getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH);
                btnRegistrarse.setIcon(new javax.swing.ImageIcon(imgReg));
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudieron cargar los iconos", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymPower Gimnasio");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(25, 25, 25));

        lblTitulo.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 48));
        lblTitulo.setForeground(new java.awt.Color(255,255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("GymPower");
        lblTitulo.setName("lblTitulo");

        lblSubtitulo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        lblSubtitulo.setForeground(new java.awt.Color(200,200,200));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Gimnasio & Wellness");
        lblSubtitulo.setName("lblSubtitulo");

        separador.setForeground(new java.awt.Color(200, 200, 200));
        separador.setName("separador");

        btnIniciarSesion.setBackground(new java.awt.Color(52, 120, 200));
        btnIniciarSesion.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setName("btnIniciarSesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnRegistrarse.setBackground(new java.awt.Color(0, 153,76));
        btnRegistrarse.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        btnRegistrarse.setForeground(new java.awt.Color(255,255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 120, 200)));
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setFocusPainted(false);
        btnRegistrarse.setName("btnRegistrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        lblBienvenida.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 16));
        lblBienvenida.setForeground(new java.awt.Color(220,220,220));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Desarrollado por Andres Vargas y Jeison Diaz");
        lblBienvenida.setName("lblBienvenida");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(separador)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTitulo)
                .addGap(10, 10, 10)
                .addComponent(lblSubtitulo)
                .addGap(40, 40, 40)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblBienvenida)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * Abre la ventana de inicio de sesion y cierra la actual.
     * @param evt evento del boton
     */
    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        new InicioSesion();
        dispose();
    }

    /**
     * Abre la ventana de registro y cierra la actual.
     * @param evt evento del boton
     */
    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {
        new Registrarse();
        dispose();
    }

    /**
     * Metodo principal que lanza la aplicacion.
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JSeparator separador;
    // End of variables declaration
}
