/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Menu principal del entrenador en GymPower.
 * Muestra las citas agendadas con el entrenador en una JTable.
 * @author andre
 */
public class MenuEntrenador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuEntrenador.class.getName());

    /** Entrenador con sesion activa */
    private Entrenador entrenador;

    /**
     * Constructor: recibe el entrenador autenticado y construye el menu.
     * @param entrenador objeto Entrenador con la sesion activa
     */
    public MenuEntrenador(Entrenador entrenador) {
        this.entrenador = entrenador;
        initComponents();
        setLocationRelativeTo(null);
        configurarVentana();
        cargarIconosBotones();
        cargarTablaCitas();
        setVisible(true);
    }

    /**
     * Configura titulo y etiquetas con los datos del entrenador autenticado.
     */
    private void configurarVentana() {
        setTitle("Menu Entrenador - " + entrenador.getNombre());
        lblNombre.setText("Entrenador: " + entrenador.getNombre());
        lblEspecialidad.setText("Especialidad: " + entrenador.getEspecialidad());
    }

    /**
     * Carga el icono en el boton de cerrar sesion.
     */
    private void cargarIconosBotones() {
        try {
            java.net.URL url = getClass().getResource("/imagenes/salir.png");
            if (url != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
                java.awt.Image img = icon.getImage().getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
                btnSalir.setIcon(new javax.swing.ImageIcon(img));
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.WARNING, "Icono no encontrado", ex);
        }
    }

    /**
     * Rellena la JTable con las citas asignadas al entrenador.
     * Consulta el DataManager por usuario del entrenador.
     */
    private void cargarTablaCitas() {
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCitas.getModel();
        modelo.setRowCount(0);

        java.util.List<Cita> citas = DataManager.citasPorEntrenador(entrenador.getUsuario());
        for (Cita c : citas) {
            modelo.addRow(new Object[]{
                c.getUsuarioCliente(),
                c.getFecha(),
                c.getHora(),
                c.getMotivo()
            });
        }

        if (citas.isEmpty()) {
            lblEstadoCitas.setText("No tienes citas asignadas.");
        } else {
            lblEstadoCitas.setText("Citas asignadas: " + citas.size());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        panelCitas = new javax.swing.JPanel();
        lblTituloCitas = new javax.swing.JLabel();
        scrollCitas = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        lblEstadoCitas = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Entrenador");
        setResizable(false);

        // Panel info entrenador
        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 5, 15));
        panelInfo.setName("panelInfo");

        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        lblNombre.setText("Entrenador:");
        lblNombre.setName("lblNombre");

        lblEspecialidad.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        lblEspecialidad.setForeground(new java.awt.Color(80, 80, 80));
        lblEspecialidad.setText("Especialidad:");
        lblEspecialidad.setName("lblEspecialidad");

        separador.setName("separador");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(lblEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(separador)
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(lblNombre)
                .addGap(3, 3, 3)
                .addComponent(lblEspecialidad)
                .addGap(8, 8, 8)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        // Panel de la tabla de citas
        panelCitas.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 10, 15));
        panelCitas.setName("panelCitas");

        lblTituloCitas.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblTituloCitas.setText("Mis citas agendadas:");
        lblTituloCitas.setName("lblTituloCitas");

        // JTable con citas del entrenador
        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Cliente", "Fecha", "Hora", "Motivo"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        tblCitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCitas.setName("tblCitas");
        tblCitas.getTableHeader().setReorderingAllowed(false);
        scrollCitas.setViewportView(tblCitas);
        scrollCitas.setName("scrollCitas");

        lblEstadoCitas.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 13));
        lblEstadoCitas.setForeground(new java.awt.Color(130, 130, 130));
        lblEstadoCitas.setText("Cargando...");
        lblEstadoCitas.setName("lblEstadoCitas");

        btnActualizar.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setName("btnActualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        btnSalir.setText("Cerrar Sesion");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setName("btnSalir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(scrollCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(lblEstadoCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitasLayout.createSequentialGroup()
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addComponent(lblTituloCitas)
                .addGap(4, 4, 4)
                .addComponent(scrollCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblEstadoCitas)
                .addGap(10, 10, 10)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(800, 600);
        pack();
    }// </editor-fold>

    /**
     * Recarga la tabla de citas desde el archivo.
     * @param evt evento del boton Actualizar
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {
        cargarTablaCitas();
    }

    /**
     * Cierra sesion y regresa a la ventana de inicio.
     * @param evt evento del boton Cerrar Sesion
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        new Inicio();
        dispose();
    }

    /**
     * Metodo principal para pruebas directas de esta ventana.
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Entrenador demo = new Entrenador("Carlos Demo", "Musculacion", "carlos", "1234");
            new MenuEntrenador(demo).setVisible(true);
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblEstadoCitas;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloCitas;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollCitas;
    private javax.swing.JSeparator separador;
    private javax.swing.JTable tblCitas;
    // End of variables declaration
}
