/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Menu principal del cliente en GymPower.
 * Muestra las opciones disponibles y una tabla con las citas agendadas.
 * Usa JTable (componente no explicado en clase) para mostrar informacion tabular.
 * @author andre
 */
public class MenuCliente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCliente.class.getName());

    /** Cliente que inicio sesion actualmente */
    private Cliente cliente;

    /**
     * Constructor: recibe el cliente autenticado y construye el menu.
     * @param cliente objeto Cliente con la sesion activa
     */
    public MenuCliente(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
        setLocationRelativeTo(null);
        configurarVentana();
        cargarIconosBotones();
        cargarTablaCitas();
        setVisible(true);
    }

    /**
     * Configura el titulo de la ventana y la etiqueta de saludo con el nombre del cliente.
     */
    private void configurarVentana() {
        setTitle("Menu Cliente - " + cliente.getNombre());
        lblSaludo.setText("Hola, " + cliente.getNombre() + " " + cliente.getApellido());

        // Verificar si tiene membresia activa
        Membresia m = DataManager.obtenerMembresiaCliente(cliente.getUsuario());
        if (m != null) {
            lblMembresia.setText("Plan activo: " + m.getPlan() +
                " - $" + String.format("%,.0f", m.calcularTotal()));
            lblMembresia.setForeground(new java.awt.Color(0, 128, 0));
        } else {
            lblMembresia.setText("Sin membresia activa");
            lblMembresia.setForeground(java.awt.Color.RED);
        }
    }

    /**
     * Carga iconos en los botones del menu.
     * Si los recursos no existen, los botones muestran solo texto.
     */
    private void cargarIconosBotones() {
        String[][] botonesPaths = {
            {"/recursos/membresia.png", "btnMembresia"},
            {"/recursos/cita.png",      "btnCita"},
            {"/recursos/salir.png",     "btnSalir"}
        };
        javax.swing.JButton[] botones = {btnMembresia, btnCita, btnSalir};
        for (int i = 0; i < botones.length; i++) {
            try {
                java.net.URL url = getClass().getResource(botonesPaths[i][0]);
                if (url != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
                    java.awt.Image img = icon.getImage().getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
                    botones[i].setIcon(new javax.swing.ImageIcon(img));
                }
            } catch (Exception ex) {
                logger.log(java.util.logging.Level.WARNING, "Icono no encontrado: " + botonesPaths[i][0], ex);
            }
        }
    }

    /**
     * Carga las citas del cliente en la JTable.
     * Consulta el DataManager y llena el modelo de la tabla.
     */
    private void cargarTablaCitas() {
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCitas.getModel();
        modelo.setRowCount(0); // Limpiar filas previas

        java.util.List<Cita> citas = DataManager.citasPorCliente(cliente.getUsuario());
        for (Cita c : citas) {
            modelo.addRow(new Object[]{
                c.getFecha(),
                c.getHora(),
                c.getEntrenador(),
                c.getMotivo()
            });
        }

        if (citas.isEmpty()) {
            lblEstadoCitas.setText("No tienes citas agendadas aun.");
        } else {
            lblEstadoCitas.setText("Total de citas: " + citas.size());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        lblSaludo = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnMembresia = new javax.swing.JButton();
        btnCita = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelCitas = new javax.swing.JPanel();
        lblTituloCitas = new javax.swing.JLabel();
        scrollCitas = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        lblEstadoCitas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Cliente");
        setResizable(false);

        // Panel de informacion del usuario
        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 5, 15));
        panelInfo.setName("panelInfo");

        lblSaludo.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        lblSaludo.setText("Hola, Cliente");
        lblSaludo.setName("lblSaludo");

        lblMembresia.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        lblMembresia.setText("Sin membresia activa");
        lblMembresia.setForeground(java.awt.Color.RED);
        lblMembresia.setName("lblMembresia");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(lblMembresia, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(lblSaludo)
                .addGap(4, 4, 4)
                .addComponent(lblMembresia))
        );

        // Panel de botones
        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        panelBotones.setLayout(new java.awt.GridLayout(1, 3, 8, 0));
        panelBotones.setName("panelBotones");

        btnMembresia.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        btnMembresia.setText("Ver Membresia");
        btnMembresia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMembresia.setName("btnMembresia");
        btnMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMembresiaActionPerformed(evt);
            }
        });
        panelBotones.add(btnMembresia);

        btnCita.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        btnCita.setText("Agendar Cita");
        btnCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCita.setName("btnCita");
        btnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaActionPerformed(evt);
            }
        });
        panelBotones.add(btnCita);

        btnSalir.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        btnSalir.setText("Cerrar Sesion");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setName("btnSalir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelBotones.add(btnSalir);

        // Panel de tabla de citas
        panelCitas.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 10, 15));
        panelCitas.setName("panelCitas");

        lblTituloCitas.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblTituloCitas.setText("Mis Citas:");
        lblTituloCitas.setName("lblTituloCitas");

        // JTable: componente no explicado en clase
        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Fecha", "Hora", "Entrenador", "Motivo"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // La tabla no es editable
            }
        });
        tblCitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCitas.setName("tblCitas");
        tblCitas.getTableHeader().setReorderingAllowed(false);
        scrollCitas.setViewportView(tblCitas);
        scrollCitas.setName("scrollCitas");

        lblEstadoCitas.setFont(new java.awt.Font("Arial", java.awt.Font.ITALIC, 13));
        lblEstadoCitas.setForeground(new java.awt.Color(130, 130, 130));
        lblEstadoCitas.setText("Cargando citas...");
        lblEstadoCitas.setName("lblEstadoCitas");

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(scrollCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addComponent(lblEstadoCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addComponent(lblTituloCitas)
                .addGap(4, 4, 4)
                .addComponent(scrollCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblEstadoCitas))
        );

        // Layout principal
        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(panelCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(800, 600);
        pack();
    }// </editor-fold>

    /**
     * Navega a la ventana de seleccion de membresia.
     * @param evt evento del boton
     */
    private void btnMembresiaActionPerformed(java.awt.event.ActionEvent evt) {
        new ListaMembresia(cliente);
        dispose();
    }

    /**
     * Navega a la ventana de confirmacion de cita.
     * @param evt evento del boton
     */
    private void btnCitaActionPerformed(java.awt.event.ActionEvent evt) {
        new ConfirmarCita(cliente);
        dispose();
    }

    /**
     * Cierra la sesion y regresa a la ventana de inicio.
     * @param evt evento del boton
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        new Inicio();
        dispose();
    }

    /**
     * Metodo principal para lanzar el menu directamente (pruebas).
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCliente.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Cliente demo = new Cliente("Demo", "User", "demo", "1234", "demo@gym.com");
            new MenuCliente(demo).setVisible(true);
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnMembresia;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblEstadoCitas;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JLabel lblTituloCitas;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCitas;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollCitas;
    private javax.swing.JTable tblCitas;
    // End of variables declaration
}
