/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Ventana de registro de nuevos clientes en GymPower.
 * Valida los datos ingresados y guarda el nuevo cliente en el archivo CSV.
 * @author andre
 */
public class Registrarse extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrarse.class.getName());

    /**
     * Constructor: inicializa la ventana de registro.
     */
    public Registrarse() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelRegistro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        lblConfirmar = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JPasswordField();
        btnCrearCuenta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrarse - GymPower");
        setResizable(false);

        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblNombre.setText("Nombre:");
        lblNombre.setName("lblNombre");

        txtNombre.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtNombre.setName("txtNombre");

        lblApellido.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblApellido.setText("Apellido:");
        lblApellido.setName("lblApellido");

        txtApellido.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtApellido.setName("txtApellido");

        lblUsuario.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblUsuario.setText("Usuario:");
        lblUsuario.setName("lblUsuario");

        txtUsuario.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtUsuario.setName("txtUsuario");

        lblCorreo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblCorreo.setText("Correo:");
        lblCorreo.setName("lblCorreo");

        txtCorreo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtCorreo.setName("txtCorreo");

        lblContrasena.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblContrasena.setText("Contrasena:");
        lblContrasena.setName("lblContrasena");

        txtContrasena.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtContrasena.setName("txtContrasena");

        lblConfirmar.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        lblConfirmar.setText("Confirmar contrasena:");
        lblConfirmar.setName("lblConfirmar");

        txtConfirmar.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 15));
        txtConfirmar.setName("txtConfirmar");

        btnCrearCuenta.setBackground(new java.awt.Color(52, 120, 200));
        btnCrearCuenta.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCuenta.setFocusPainted(false);
        btnCrearCuenta.setName("btnCrearCuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setName("btnVolver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblUsuario)
                    .addComponent(lblCorreo)
                    .addComponent(lblContrasena)
                    .addComponent(lblConfirmar))
                .addGap(30, 30, 30)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txtApellido)
                    .addComponent(txtUsuario)
                    .addComponent(txtCorreo)
                    .addComponent(txtContrasena)
                    .addComponent(txtConfirmar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroLayout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(btnCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                .addGap(100, 100, 100))
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmar)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * Ejecuta el proceso de registro cuando se hace clic en "Crear Cuenta".
     * @param evt evento del boton
     */
    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {
        registrar();
    }

    /**
     * Regresa a la ventana de inicio.
     * @param evt evento del boton
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {
        new Inicio();
        dispose();
    }

    /**
     * Valida los campos y registra el nuevo cliente.
     * Verifica que las contrasenas coincidan, que el usuario no exista,
     * que el correo tenga '@', y que la contrasena tenga minimo 4 caracteres.
     */
    private void registrar() {
        String nombre    = txtNombre.getText().trim();
        String apellido  = txtApellido.getText().trim();
        String usuario   = txtUsuario.getText().trim();
        String correo    = txtCorreo.getText().trim();
        String pass      = new String(txtContrasena.getPassword()).trim();
        String confirmar = new String(txtConfirmar.getPassword()).trim();

        // Validacion de campos vacios
        if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() ||
            correo.isEmpty() || pass.isEmpty() || confirmar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Validacion de contrasenas
        if (!pass.equals(confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Las contrasenas no coinciden.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Longitud minima
        if (pass.length() < 4) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La contrasena debe tener al menos 4 caracteres.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Usuario unico
        if (DataManager.usuarioExiste(usuario)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El nombre de usuario ya esta en uso.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Correo con @
        if (!correo.contains("@")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor ingresa un correo valido.", "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Guardar el nuevo cliente
        Cliente nuevo = new Cliente(nombre, apellido, usuario, pass, correo);
        DataManager.guardarCliente(nuevo);

        javax.swing.JOptionPane.showMessageDialog(this,
            "Cuenta creada exitosamente!\nYa puedes iniciar sesion, " + nombre + ".",
            "Registro exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        new InicioSesion();
        dispose();
    }

    /**
     * Metodo principal para ejecutar esta ventana directamente.
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrarse().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration
}
